<?php

$frontControllerName = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
$frontActionName     = Zend_Controller_Front::getInstance()->getRequest()->getActionName();

$this->headTitle('Danica Boleto')->setSeparator(' | ');

$this->headMeta()->prependHttpEquiv('Content-Type','text/html; charset=UTF-8');
$this->headMeta()->prependHttpEquiv('X-UA-Compatible','IE=edge');
$this->headMeta()->prependHttpEquiv('content-language',strtolower(str_replace('_','-',Zend_Registry::get('Zend_Locale'))));

// $this->headLink()->appendStylesheet($this->baseUrl('styles/default/reset.css'),'screen');
// $this->headLink()->appendStylesheet($this->baseUrl('styles/default/layout.css'),'screen');
// $this->headLink(array('rel' => 'shortcut icon','href' => $this->url(array(),'media-index') . 'styles/default/images/favicon.png'));
// $this->headLink(array('rel' => 'canonical','href' => $this->url()));

$this->headScript()->appendFile($this->baseUrl('js/jquery.js'));
$this->headScript()->appendFile($this->baseUrl('js/bootstrap.min.js'));
$this->headScript()->appendFile($this->baseUrl('js/main.js'));
// $this->headScript()->appendFile($this->baseUrl('scripts/library/jquery.animate.easing/jquery.easing.1.3.js'));
// $this->headScript()->appendFile($this->baseUrl('scripts/library/jquery.masonry/jquery.masonry.min.js'));
// $this->headScript()->appendFile($this->baseUrl('scripts/library/jquery.form.mask/jquery.meio.mask.min.js'));
// $this->headScript()->appendFile($this->baseUrl('scripts/library/cufon/cufon-yui.js'));
// $this->headScript()->appendFile($this->baseUrl('scripts/default/cufon/DTLNobelT_Light_300-DTLNobelT_Light_italic_300.font.js'));
// $this->headScript()->appendFile($this->baseUrl('scripts/default/cufon/DTLNobelT_400.font.js'));
// $this->headScript()->appendFile($this->baseUrl('js/library.js'));
// $this->headScript()->appendFile($this->baseUrl('build/JST.js'));
// $this->headScript()->appendFile($this->baseUrl('build/min.js'));
$this->headLink()->appendStylesheet($this->baseUrl('css/lib.css'),'screen');
$this->headLink()->appendStylesheet($this->baseUrl('css/font-awesome.min.css'),'screen');
$this->headLink()->appendStylesheet($this->baseUrl('css/main.css'),'screen');


?>
<!DOCTYPE html> 
<html ng-app='app'lang="pt-BR">

	<head>
		<!-- Latest compiled and minified CSS -->
		<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700' rel='stylesheet' type='text/css'>

		<!-- Optional theme -->

		<!-- Latest compiled and minified JavaScript -->
		<?php 
		$tipo = Zend_Auth::getInstance()->getIdentity()->tipo;
		echo $this->headTitle()->toString() . "\r\n";
		echo $this->headMeta()->toString() . "\r\n";
		echo (APPLICATION_ENV == 'development'  ? $this->headLink()->toString() : $this->compressStyle()) . "\r\n";
		echo $this->navigation()->setRole('Guest')->links();
		?>
	</head>

	<body>
		<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="/"><i class="fa fa-newspaper-o"></i> Dânica Boletos</a>
				</div>
				<div id="navbar" class="navbar-collapse collapse">
					<ul class="nav navbar-nav navbar-right">
						<li><a href="/">Boletos</a></li>
						<?php if ($tipo == 'admin'): ?>
						<li><a href="/usuarios">Usuários</a></li>
						<?php endif ?>
						
						<li>
							<a href="#" data-toggle="modal" data-target="#modalUsuario">Minha Conta</a>
							<!-- Modal -->
							<?php $row = Zend_Auth::getInstance()->getIdentity(); ?>
							<div class="modal fade" id="modalUsuario" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
							  <div class="modal-dialog">
							    <div class="modal-content">
						        	<form action="/usuarios/alterar-senha" class="form-usuario">
							      <div class="modal-header">
							        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
							        <h4 class="modal-title" id="myModalLabel">Minha Conta</h4>
							      </div>
							      <div class="modal-body">
									  <div class="form-group">
									    <label for="">E-mail</label> <br>
									    <code><?php echo $row->email ?></code>
									    <input type="hidden" name="email" class="form-usuario-email" value="<?php echo $row->email ?>">
									  </div>
									  <div class="form-group">
									    <label for="nome">Nome</label>
									    <input type="text" class="form-control form-usuario-nome" name="nome" required placeholder="Nome" value="<?php echo $row->nome ?>">
									  </div>
									  <div class="form-group">
									  	<div style="display: inline-block; width: 59%">
										    <label for="nome">Cidade</label>
										    <input type="text" class="form-control form-usuario-cidade" name="cidade" required placeholder="Cidade" value="<?php echo $row->cidade ?>">
									    </div>
									  	<div style="display: inline-block; width: 39%">
										    <label for="estado">Estado</label>
										    <input type="text" class="form-control form-usuario-estado" name="estado" required placeholder="Estado" value="<?php echo $row->estado ?>">
									    </div>
									  </div>
									  <?php if ($row->tipo == 'admin'): ?>
									  <div class="form-group">
									    <label for="tipo">Tipo de usuário</label> <br>
									    <select name="tipo" class="form-usuario-tipo">
									    	<option value="member" <?php echo $row->tipo == 'member' ? 'selected' : '' ?>>Usuário</option>
									    	<option value="admin" <?php echo $row->tipo == 'admin' ? 'selected' : '' ?>>Administrador</option>
									    </select>
									  </div>
									  <?php endif ?>
									  <div class="form-group">
									    <label for="senha">Nova Senha</label>
									    <input type="password" class="form-control form-usuario-senha"  name="senha" placeholder="Nova Senha">
									  </div>
									  <div class="form-group">
									    <label for="nova-senha">Repita Nova Senha</label>
									    <input type="password" class="form-control form-usuario-nova-senha"   name="nova-senha" placeholder="Repita Nova Senha">
									  </div>
							      </div>
							      <div class="modal-footer">
							        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
							        <button type="submit" class="btn btn-primary">Salvar</button>
							      </div>
									</form>
							    </div>
							  </div>
							</div>
						</li>
						<li><a href="/sessao/logout">Sair</a></li>
					</ul>
				</div>
			</div>
		</nav>
		<?php if (Zend_Controller_Front::getInstance()->getRequest()->getParam('message') != ''): ?>
			<div class="container">
				<br>
				<div class="alert alert-<?php echo Zend_Controller_Front::getInstance()->getRequest()->getParam('message-type'); ?> alert-dismissible fade in" role="alert">
			      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">×</span><span class="sr-only">Fechar</span></button>
			      <?php echo Zend_Controller_Front::getInstance()->getRequest()->getParam('message'); ?>
			    </div>
			</div>
		<?php endif ?>

		<?php echo $this->layout()->content ?>

	  	<?php echo (APPLICATION_ENV == 'development'  ? $this->headScript()->toString() :  $this->compressScript()) . "\r\n"; ?>
	</body>
</html>

