<form class="form-signin" role="form" action="/sessao/login">
    <h2 class="form-signin-heading ">Boleto Dânica</h2>
    <h3 class="form-signin-heading">Acesso Restrito</h3>
    <label for="inputEmail" class="sr-only">E-mail</label>
    <input type="email" id="inputEmail" class="form-control" placeholder="E-mail" required autofocus>
    <label for="inputPassword" class="sr-only">Senha</label>
    <input type="password" id="inputPassword" class="form-control" placeholder="Senha" required>
    <button class="btn btn-lg btn-primary btn-block" type="submit">Acessar</button>
</form>